### ISSUE TITLE
Ruins Invalid Data GS55 L05

### ISSUE THREAD

**Issue by CMDRMadMalik** [canonn-science/RuinsComboMap#15]
## Your CMDR Name: 
Example: CMDR MadMalik

## Which Ruins Site? 
Example: GS55

## Which Obelisk ID? 
Example: L05

## What data did you get? 
Example: None, inactive obelisk

## What combo did you use? 
Example: Unable to interact with the obelisk, it would not light up.

## Other Questions/Comments/Concerns
Unable to interact with the obelisk in open or solo mode, multiple logout/login attempts made.

**Comment by derrickmehaffy** [comment]
Reported on Data Sheet pending further Canonn Review, API not modified yet.

**Comment by derrickmehaffy** [comment]
Per Supafuzz916:

GS55 L05 not lit up. Can confirm it is not lit, however according to the active obelisks spreadsheet it was not supposed to be lit as I reported L06 as the only active in the L cluster. Also the map does not show L05 lit in the API only L06. Not sure on this one but you can close it because L05 is definatly not lit.

Also due to the report, marking this issue as resolved.
